name: Release Binares

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:

  release_win64:
    name: Build and release Windows 64Bit
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Build
        run: |
          cargo build --release
          Compress-Archive -LiteralPath target/release/odbcsv.exe -DestinationPath odbcsv-win64.zip

      - name: Github Upload
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          file: odbcsv-win64.zip
          asset_name: odbcsv-win64.zip
          tag: ${{ github.ref }}
  
  release_win32:
    name: Build and release Windows 32Bit
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Build
        run: |
          cargo build --release
          Compress-Archive -LiteralPath target/release/odbcsv.exe -DestinationPath odbcsv-win32.zip

      - name: Github Upload
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          file: odbcsv-win32.zip
          asset_name: odbcsv-win32.zip
          tag: ${{ github.ref }}

  release_os-x:
    name: Build and release OS-X
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Install unixODBC
        run: |
          brew install unixodbc

      - name: Build
        run: cargo build --release

      - name: Github Upload
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          file: target/release/odbcsv
          asset_name: odbcsv-osx
          tag: ${{ github.ref }}