name: Release Binares

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:

  release_win64:
    name: Build and release Windows 64Bit
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          cargo build --release
          Compress-Archive -LiteralPath target/release/odbcsv.exe -DestinationPath odbcsv-win64.zip

      - name: Github Upload
        uses: svenstaro/upload-release-action@v2
        with:
          file: odbcsv-win64.zip
          asset_name: odbcsv-win64.zip
          tag: ${{ github.ref }}
  
  release_win32:
    name: Build and release Windows 32Bit
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          cargo build --release
          Compress-Archive -LiteralPath target/release/odbcsv.exe -DestinationPath odbcsv-win32.zip

      - name: Github Upload
        uses: svenstaro/upload-release-action@v2
        with:
          file: odbcsv-win32.zip
          asset_name: odbcsv-win32.zip
          tag: ${{ github.ref }}

  release_os-x:
    name: Build and release OS-X
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install unixODBC
        run: |
          brew install unixodbc
          sudo ln -s /opt/homebrew/lib ~/lib

      - name: Build
        run: cargo build --release

      - name: Github Upload
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/odbcsv
          asset_name: odbcsv-osx
          tag: ${{ github.ref }}